feat : delete datasource functionality
databrokerglobal/dxc pull request #379
Opened 2020-10-15 12:31 UTC by ManishChain

There is a DELTE button for each datasource and popup a confirmation dialog upon action

As discussed with Vincent, we can implement the delete function at this stage; together with other tasks; and keep the “edit” for later version. view JIRA issue https://settlemint.atlassian.net/browse/DDX-6

2020-10-15 12:32 UTC, ManishChain commented
@woodyjon Can you help me identifying why tests are failing ?

2020-10-19 04:33 UTC, ManishChain commented
@woodyjon Could you please update on this PR ? If you can help me on this failing checks then it would be great. I am not able to resolve these.

2020-10-19 09:35 UTC, ManishChain commented
@goosecoid  Steps
1. Clone branch
2. Optionally configure .env 
3. cd dxc <root folder>
4. Issue command: go run server.go 
5. Another terminal: cd <root>/ui 
6. Issue command: npm run start
7. localhost:3000 started in browser

DELETE feature
1. Add few datasources 
2. Each datasource have DELETE button. On click of it, confirm dialog appears. If you click OK then datasource is deleted  

EDIT
1. Add few datasources
2. Each datasource have DELETE button. On click of it, confirm dialog appears. 
3. If you click OK then it prompt to enter "NAME" and/or "HOST" Once you edit any of those, previous one is deleted and new datasource is added.

2020-10-20 07:47 UTC, woodyjon requested changes

2020-10-20 07:47 UTC, woodyjon commented on ui/src/Datasources.tsx
> +              await axios.post(`${LOCAL_HOST}/datasource`, body, {
There is already a route to update datasources. Please do not post a new one and delete the old one. That would mean the did would change.

2020-10-20 07:47 UTC, woodyjon commented on ui/src/Datasources.tsx
> +                      <Button variant="contained" onClick={e => handleEdit(datasource)}>Edit</Button>&nbsp;&nbsp;&nbsp;
Please use margins or paddings, instead of &nbsp.

2020-10-20 07:55 UTC, ManishChain commented on ui/src/Datasources.tsx
> +              await axios.post(`${LOCAL_HOST}/datasource`, body, {
Ok Jon. Thanks for update and I will revert the changes and try to use the existing route.

2020-10-20 11:00 UTC, ManishChain commented on ui/src/Datasources.tsx
> +                      <Button variant="contained" onClick={e => handleEdit(datasource)}>Edit</Button>&nbsp;&nbsp;&nbsp;
Done

2020-10-21 05:08 UTC, ManishChain commented
@goosecoid @woodyjon The test case for update feature testing is TestUpdateDatasourceByDID(). But the issue is that I am not able to retrieve the same datasource again ..see function TestUpdateDatasourceByDID_check()

2020-11-03 12:48 UTC, goosecoid approved these changes

2020-11-04 09:31 UTC, merged